// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ArticleImage$ReactTemplate = require("./ArticleImage.bs.js");

var component = ReasonReact.statelessComponent("Article");

function make(article, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var match = article[/* description */3];
              return React.createElement("article", {
                          className: "p-3 w-1/3"
                        }, React.createElement("div", {
                              className: "max-w-sm rounded overflow-hidden shadow-lg"
                            }, ReasonReact.element(undefined, undefined, ArticleImage$ReactTemplate.make(article[/* title */2], article[/* urlToImage */5], /* array */[])), React.createElement("div", {
                                  className: "px-6 py-4"
                                }, React.createElement("div", {
                                      className: "font-bold text-xl mb-2"
                                    }, article[/* title */2]), React.createElement("p", {
                                      className: "text-grey-darker text-base"
                                    }, match !== undefined ? match : null), React.createElement("div", {
                                      className: "flex items-center mt-3"
                                    }, React.createElement("div", {
                                          className: "text-sm"
                                        }, React.createElement("p", {
                                              className: "text-grey-dark"
                                            }, article[/* publishedAt */6]))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
