// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Article$ReactTemplate = require("./Article.bs.js");
var NewsData$ReactTemplate = require("./NewsData.bs.js");

var component = ReasonReact.reducerComponent("Headlines");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              Curry._1(self[/* send */3], /* Loading */0);
              NewsData$ReactTemplate.fetchTopHeadlines("us").then((function (res) {
                      Curry._1(self[/* send */3], /* Loaded */[res[/* articles */2]]);
                      return Promise.resolve(/* () */0);
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "px-2 max-w-2xl mx-auto"
                        }, React.createElement("h1", undefined, "Headline"), React.createElement("div", {
                              className: "flex flex-wrap"
                            }, self[/* state */1][/* articles */0].length !== 0 ? $$Array.map((function (article) {
                                      return ReasonReact.element(article[/* url */4], undefined, Article$ReactTemplate.make(article, /* array */[]));
                                    }), self[/* state */1][/* articles */0]) : null));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* articles : array */[],
                      /* loading */true
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[
                            /* articles */action[0],
                            /* loading */false
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* articles */state[/* articles */0],
                            /* loading */true
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
