// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Counter$ReactTemplate = require("./Counter.bs.js");
var Greeting$ReactTemplate = require("./Greeting.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Greeting$ReactTemplate.make("An", /* array */[])), "app");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Counter$ReactTemplate.make(/* array */[])), "counter");

/*  Not a pure module */
