// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var apiUrl = "https://newsapi.org/v2";

function topHeadlinesUrl(country) {
  return "" + (String(apiUrl) + ("/top-headlines?country=" + (String(country) + "&apiKey=dd87847a99f145368ab6fad5194ce99d")));
}

function toSource(json) {
  return /* record */[
          /* id */Json_decode.optional((function (param) {
                  return Json_decode.field("id", Json_decode.string, param);
                }), json),
          /* name */Json_decode.optional((function (param) {
                  return Json_decode.field("name", Json_decode.string, param);
                }), json)
        ];
}

function toArticle(json) {
  return /* record */[
          /* source */Json_decode.field("source", toSource, json),
          /* author */Json_decode.optional((function (param) {
                  return Json_decode.field("author", Json_decode.string, param);
                }), json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* description */Json_decode.optional((function (param) {
                  return Json_decode.field("description", Json_decode.string, param);
                }), json),
          /* url */Json_decode.field("url", Json_decode.string, json),
          /* urlToImage */Json_decode.optional((function (param) {
                  return Json_decode.field("urlToImage", Json_decode.string, param);
                }), json),
          /* publishedAt */Json_decode.field("publishedAt", Json_decode.string, json),
          /* content */Json_decode.optional((function (param) {
                  return Json_decode.field("content", Json_decode.string, param);
                }), json)
        ];
}

function toArticles(json) {
  return Json_decode.array(toArticle, json);
}

function toResponse(json) {
  return /* record */[
          /* status */Json_decode.field("status", Json_decode.string, json),
          /* totalResults */Json_decode.field("totalResults", Json_decode.$$int, json),
          /* articles */Json_decode.field("articles", toArticles, json)
        ];
}

var Decode = /* module */[
  /* toSource */toSource,
  /* toArticle */toArticle,
  /* toArticles */toArticles,
  /* toResponse */toResponse
];

function fetchTopHeadlines(country) {
  return fetch(topHeadlinesUrl(country)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(toResponse(json));
              }));
}

exports.apiUrl = apiUrl;
exports.topHeadlinesUrl = topHeadlinesUrl;
exports.Decode = Decode;
exports.fetchTopHeadlines = fetchTopHeadlines;
/* No side effect */
