// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Button$ReactTemplate = require("./Button.bs.js");
var Greeting$ReactTemplate = require("./Greeting.bs.js");

var component = ReasonReact.reducerComponent("SimpleRouter");

function reducer(action, _) {
  return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
}

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match) {
    return /* NotFound */1;
  } else {
    return /* Home */0;
  }
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherId = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      var match = url[/* path */0];
                      if (match && match[0] === "/" && !match[1]) {
                        return Curry._1(self[/* send */3], /* ChangeRoute */[/* Home */0]);
                      } else {
                        return Curry._1(self[/* send */3], /* ChangeRoute */[/* NotFound */1]);
                      }
                    }));
              return Curry._1(self[/* onUnmount */4], (function () {
                            return ReasonReact.Router[/* unwatchUrl */2](watcherId);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* route */0];
              if (match) {
                return React.createElement("h1", undefined, "Not Found");
              } else {
                return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Greeting$ReactTemplate.make("An", /* array */[])), ReasonReact.element(undefined, undefined, Button$ReactTemplate.make((function () {
                                      return ReasonReact.Router[/* push */0]("/whatever");
                                    }), /* array */["Change"])));
              }
            }),
          /* initialState */(function () {
              return /* record */[/* route : Home */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.reducer = reducer;
exports.mapUrlToRoute = mapUrlToRoute;
exports.make = make;
/* component Not a pure module */
